export function langpack(lang) {
  let langpack;
  if (lang === "ru") {
    langpack = {
      main: {
        join_squad: "Присоединяйся к отряду",
        bronze: "Бронза",
        silver: "Серебро",
        gold: "Золото",
        platinum: "Платина",
        diamond: "Бриллиант",
        frens: "Друзья",
        earn: "Заработай!",
        compete: "Состязания",
      },
      squad: {
        title: "Залетай в отряд",
        these_squads_receruiting_now: "Эти отряды активно набирают игроков",
        do_you_wanna_join: "Выбирай любой",
        empty_squad: "Здесь ничего нет",
        under_maintenance: "Временно недоступно",
      },
      about: {
        join: "Канал",
        follow: "Твиттер",
        card_title_play: "Находи алмазы",
        card_text_play: "И получай Pixelcoin",
        card_title_earn: "Прокачивай бусты",
        card_text_earn: "И зарабатывай выполняя задания",
        card_title_league: "Соревнуйся с другими",
        card_text_league: "Участвуй в лигах и турнирах",
        card_title_rocket: "Лови ракету",
        card_text_rocket: "Чтобы получить больше монет",
        card_title_squad: "Вступай в отряд",
        card_text_squad: "Вместе веселее",
        full_guide: "Полное руководство",
        play: "Играть",
      },
      earn: {
        title: "Зарабатывай больше монет",
        about: "Как работает заработок",
        invite_bonus: "Бонус за друга",
        up_to: "до 120,000",
        for_fren: "за друга",
        onboarding: "Выполняй задания",
        invite_five_frens: "Пригласи 5 друзей",
        invite_ten_frens: "Пригласи 10 друзей",
        join_squad: "Присоединись к отряду",
        completed: "Выполнено",
      },
      stats: {
        balance_text_fiat: "Общий Pixelcoin баланс",
        total_players: "Всего игроков",
        daily_users: "Ежедневные пользователи",
        online: "В сети",
        invite_a_fren: "Пригласить друга",
      },
      party_kings: {
        title: "Короли вечеринок",
        description: "Пригласи больше друзей, чтобы попасть сюда",
        invite_frens: "Пригласить друзей",
      },
      qr_code: {
        desktop_is_boring: "Компьютер скучный.",
        play_on_your_mobile: "Играй на своем телефоне.",
      },
      referral: {
        title_invite: "Бонусы за друзей",
        invite_fren: "Пригласить друга",
        for_you_and_fren: "тебе и другу",
        fren_with: "Друг с",
        telegram_premium: "Телеграм премиум",
        title_level: "Бонус за переход друга в новую лигу",
        level_up: "Новая лига",
        regular_fren: "За друга",
        premium: "Премиум",
        silver: "Серебро",
        gold: "Золото",
        platinum: "Платина",
        diamonds: "Бриллиант",
        invite_a_fren: "Пригласить друга",
      },
      fren: {
        title: "Френдзона",
        top: "Топ 300",
        leaders: "лидеры",
        title_invite: "Пригласи друзей, получи бонус",
        invite_fren: "Пригласить друга",
        for_you_and_fren: "для тебя и друга",
        fren_with: "Друг с",
        telegram_premium: "Телеграм премиум",
        open_details: "Открыть детали",
        title_frens_list: "Список друзей",
        empty_frens_list: "Друзей пока нет",
        under_maintenance: "Временно недоступно",
        invite_a_fren: "Пригласить друга",
      },
      league: {
        pixelcoiners: "Пикселькоинеры",
        stats: "Статы",
        bronze_league: "Бронзовая лига",
        silver_league: "Серебряная лига",
        gold_league: "Золотая лига",
        platinum_league: "Платиновая лига",
        diamond_league: "Бриллиантовая лига",
        miners: "Майнеры",
        squads: "Отряды",
        empty_list: "Здесь ничего нет",
        under_maintenance: "Временно недоступно",
        you_will_join_leaderboard: "Вы присоединитесь к таблице лидеров",
        in_the_silver_league: "в Серебряной лиге",
        leaderboard_is_under_construction:
          "Таблица лидеров находится в разработке",
        bronze_miners: "от 0 Pixelcoin",
        bronze_squads: "от 0 Pixelcoin",
        silver_miners: "от 30K Pixelcoin",
        silver_squads: "от 3M Pixelcoin",
        gold_miners: "от 200K Pixelcoin",
        gold_squads: "от 20M Pixelcoin",
        platinum_miners: "от 500K Pixelcoin",
        platinum_squads: "от 50M Pixelcoin",
        diamond_miners: "от 1M Pixelcoin",
        diamond_squads: "от 100M Pixelcoin",
      },
      compete: {
        title: "Состязания",
        play_tournaments_and_earn_coins: "Участвуй в турнирах и зарабатывай монеты.",
        do_you_wanna_join: "Хочешь присоединиться?",
        empty_tournaments: "Здесь ничего нет",
        under_maintenance: "Временно недоступно",
      },
      referral_system: {
        play_and_earn: "%D0%98%D0%B3%D1%80%D0%B0%D0%B9%20%D0%B8%20%D0%B7%D0%B0%D1%80%D0%B0%D0%B1%D0%B0%D1%82%D1%8B%D0%B2%D0%B0%D0%B9%0A%F0%9F%8E%81%20%2B",
        for_you_and_fren: "%20Pixelcoin%20%D0%B4%D0%BB%D1%8F%20%D1%82%D0%B5%D0%B1%D1%8F%20%D0%B8%20%D0%B4%D1%80%D1%83%D0%B3%D0%B0",
      },
    };
  } else {
    langpack = {
      main: {
        join_squad: "Join squad",
        bronze: "Bronze",
        silver: "Silver",
        gold: "Gold",
        platinum: "Platinum",
        diamond: "Diamond",
        frens: "Frens",
        earn: "Earn!",
        compete: "Compete",
      },
      squad: {
        title: "Join Squad!",
        these_squads_receruiting_now: "These squads receruitiing now.",
        do_you_wanna_join: "Do you wanna join?",
        empty_squad: "There is nothing here",
        under_maintenance: "Under maintenance",
      },
      about: {
        join: "Join",
        follow: "Follow",
        card_title_play: "Find Diamonds",
        card_text_play: "And earn Pixelcoin",
        card_title_earn: "Upgrade your Boosts",
        card_text_earn: "And earn coins by completing tasks",
        card_title_league: "Climb to the top",
        card_text_league: "Participate in leagues and tournaments",
        card_title_rocket: "Catch the rocket",
        card_text_rocket: "To get more coins",
        card_title_squad: "Join Squad!",
        card_text_squad: "More fun together",
        full_guide: "Full guide",
        play: "Play",
      },
      earn: {
        title: "Earn more coins",
        about: "How earn works",
        invite_bonus: "Invite bonus",
        up_to: "up to 120,000",
        for_fren: "for fren",
        onboarding: "Onboarding",
        invite_five_frens: "Invite 5 frens",
        invite_ten_frens: "Invite 10 frens",
        join_squad: "Join squad",
        completed: "Completed",
      },
      stats: {
        balance_text_fiat: "Total Pixelcoin Balance",
        total_players: "Total Players",
        daily_users: "Daily Users",
        online: "Online",
        invite_a_fren: "Invite a fren",
      },
      party_kings: {
        title: "Party Kings",
        description: "Invite more frens to get here",
        invite_frens: "Invite frens",
      },
      qr_code: {
        desktop_is_boring: "Desktop is boring.",
        play_on_your_mobile: "Play on your mobile.",
      },
      referral: {
        title_invite: "Invite fren, get bonus",
        invite_fren: "Invite fren",
        for_you_and_fren: "for you and fren",
        fren_with: "Fren with",
        telegram_premium: "Telegram Premium",
        title_level: "Fren level up bonus",
        level_up: "Level up",
        regular_fren: "Regular fren",
        premium: "Premium",
        silver: "Silver",
        gold: "Gold",
        platinum: "Platinum",
        diamonds: "Diamonds",
        invite_a_fren: "Invite a fren",
      },
      fren: {
        title: "Fren zone",
        top: "Top 300",
        leaders: "leaders",
        title_invite: "Invite frens to get bonuses",
        invite_fren: "Invite fren",
        for_you_and_fren: "for you and fren",
        fren_with: "Fren with",
        telegram_premium: "Telegram Premium",
        open_details: "Open details",
        title_frens_list: "Frens List",
        empty_frens_list: "No frens yet",
        under_maintenance: "Under maintenance",
        invite_a_fren: "Invite a fren",
      },
      league: {
        pixelcoiners: "Pixelcoiners",
        stats: "Stats",
        bronze_league: "Bronze league",
        silver_league: "Silver league",
        gold_league: "Gold league",
        platinum_league: "Platinum league",
        diamond_league: "Diamond league",
        miners: "Miners",
        squads: "Squads",
        empty_list: "There is nothing here",
        under_maintenance: "Under maintenance",
        you_will_join_leaderboard: "You'll join leaderboard",
        in_the_silver_league: "in the Silver League",
        leaderboard_is_under_construction: "Leaderboard is under construction",
        bronze_miners: "from 0 Pixelcoin",
        bronze_squads: "from 0 Pixelcoin",
        silver_miners: "from 30K Pixelcoin",
        silver_squads: "from 3M Pixelcoin",
        gold_miners: "from 200K Pixelcoin",
        gold_squads: "from 20M Pixelcoin",
        platinum_miners: "from 500K Pixelcoin",
        platinum_squads: "from 50M Pixelcoin",
        diamond_miners: "from 1M Pixelcoin",
        diamond_squads: "from 100M Pixelcoin",
      },
      compete: {
        title: "Compete",
        play_tournaments_and_earn_coins: "Play tournaments and earn coins.",
        do_you_wanna_join: "Do you wanna join?",
        empty_tournaments: "There is nothing here",
        under_maintenance: "Under maintenance",
      },
      referral_system: {
        play_and_earn: "Play-to-Earn%0A%F0%9F%8E%81%20%2B",
        for_you_and_fren: "%20Pixelcoin%20for%20you%20and%20fren",
      },
    };
  }

  return langpack;
}

